services:
  php:
    build:
      context: docker/php
      args:
        PHP_VERSION: ${PHP_VERSION:-8.2.19}
    container_name: esther-api-php
    volumes:
      - .:/app
      - ./docker/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
    environment:
      APP_HTTP_PORT: ${APP_HTTP_PORT:-8080}
      APP_HTTPS_PORT: ${APP_HTTPS_PORT:-8433}

  nginx:
    image: nginx:${NGINX_VERSION:-1.24}
    container_name: esther-api-nginx
    volumes:
      - .:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "${APP_HTTP_PORT:-8080}:80"
      - "${APP_HTTPS_PORT:-8433}:433"

  mariadb:
    image: mariadb:${MARIADB_VERSION:-10.11}
    container_name: esther-api-mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-!ChangeMe!}
      MYSQL_PASSWORD: ${DB_PASSWORD:-!ChangeMe!}
      MYSQL_DATABASE: ${DB_DATABASE:-app}
      MYSQL_USER: ${DB_USER:-app}

volumes:
  mariadb-data:
