<?php

namespace App\Storage;

use App\Service\RoutesService;
use League\Flysystem\FilesystemAdapter;
use League\Flysystem\Local\LocalFilesystemAdapter;

class LocalDriver implements DriverInterface
{
    public const STORAGE_DIR = 'storage';

    private string $url;
    private string $path;

    public function __construct(
        private RoutesService $routesService
    ) {
        $this->url = $this->routesService->getLocalStorageUrl();

        $path = $this->routesService->getLocalStoragePath();

        if (\file_exists($path) && !\is_dir($path)) {
            throw new \Exception();
        }

        if (!\file_exists($path)) {
            \mkdir($path);
            \file_put_contents(
                \sprintf('%s%s.gitignore', $path, \DIRECTORY_SEPARATOR),
                \implode("\n", [
                    "# Generated by `src/Storage/LocalDriver.php`",
                    "# Do not modify.",
                    "*"
                ])
            );
        }

        $this->path = $path;
    }

    public static function getName(): string
    {
        return 'local';
    }

    public static function getConfiguration(): array
    {
        return [];
    }

    public function getAdapter(): FilesystemAdapter
    {
        return new LocalFilesystemAdapter($this->path);
    }

    public function getPublicUrl(): array
    {
        return [
            $this->url
        ];
    }
}
