<?php

namespace App\Storage;

use App\Service\RoutesService;
use League\Flysystem\FilesystemAdapter;
use League\Flysystem\Local\LocalFilesystemAdapter;

class LocalDriver implements DriverInterface
{
    private string $url;
    private string $relPath;
    private string $fullPath;

    public function __construct(
        private RoutesService $routesService
    ) {
        $this->url = $this->routesService->getAbsoluteUrl('app_index');

        $relPath = "storage";
        $fullPath = $this->routesService->buildAbsolutePath('public', $relPath);

        if (\file_exists($fullPath) && !\is_dir($fullPath)) {
            throw new \Exception();
        }

        if (!\file_exists($fullPath)) {
            \mkdir($fullPath);
            \file_put_contents(
                \sprintf('%s%s.gitignore', $fullPath, \DIRECTORY_SEPARATOR),
                \implode("\n", [
                    "# Generated by `src/Storage/LocalDriver.php`",
                    "# Do not modify.",
                    "*"
                ])
            );
        }

        $this->relPath = $relPath;
        $this->fullPath = $fullPath;
    }

    public static function getName(): string
    {
        return 'local';
    }

    public static function getConfiguration(): array
    {
        return [];
    }

    public function getAdapter(): FilesystemAdapter
    {
        return new LocalFilesystemAdapter($this->fullPath);
    }

    public function getPublicUrl(): array
    {
        return [
            \sprintf(
                "%s%s",
                $this->url,
                $this->relPath
            )
        ];
    }
}
